### PR TITLE
sign up and login logic is working

### PR DESCRIPTION
**Pull request by SIERRAT0NIN**
Sign up bug fixed. Password is now hidden.

### CODE REVIEW

**Review by alxedelweiss — CHANGES_REQUESTED** [review]
Tested and password field is indeed obscured.

The issue with error text shifting the form remains. Also, the background for the error text seems unnecessary.

**Review by LandonCramer — DISMISSED** [review]

**Comment by alxedelweiss** [comment]
I implemented the error text handling and improved on the password validation. Ready to merge

**Review by alxedelweiss — DISMISSED** [review]
Changes implemented

**Review by alxedelweiss — APPROVED** [review]
Tested and Ready to merge

**Pull request merged**
