### PR TITLE
scanReceipt, and single item view

### PR DESCRIPTION
**Pull request by LandonCramer**
I added the scanRecipt to the transactions just the camera view... Making stretch goal now
added single page transaction view

### CODE REVIEW

**Review by gingkolane — DISMISSED** [review]

**Comment by alxedelweiss** [comment]
Landon, I thought we discussed the "scan receipt" feature and decided to not proceed with it. Our transactions/expenses etc would be coming from users linking their accounts. Do we need "expo-camera" and a component for it in this case?

**Comment by LandonCramer** [comment]
Sorry for the mix up. I made it before we discussed not to proceed. I was
thinking we can leave it in and say in the future we would like to add
this. Is that possible?

**Comment by alxedelweiss** [comment]
Sure thing, it might be confusing if it is a part of the UI though. Let's discuss on Monday

**Comment by LandonCramer** [comment]
Okay sounds good to me

**Review by alxedelweiss — APPROVED** [review]
gonna move this along for now

**Pull request merged**
