### PR TITLE
Dashboard alberto

### PR DESCRIPTION
**Pull request by SIERRAT0NIN**

### CODE REVIEW

**Review by isaacsong1 — DISMISSED** [review]
looking good

**Review by LandonCramer — DISMISSED** [review]

**Comment by LandonCramer** [comment]
looks great!

**Comment by alxedelweiss** [comment]
Looks like there's a merge conflict!

**Comment by gingkolane** [comment]
Can I do something to resolve this?

**Review by gingkolane — DISMISSED** [review]

**Review by gingkolane — APPROVED** [review]

**Pull request merged**
